### ISSUE TITLE
DD4T JMS Cache Invalidation with Tridion Object Cache implemented

### ISSUE THREAD

**Issue by sameerjam** [dd4t/dd4t-cachechannel#1]
I have implemented JMS based cache invalidation mechanism using Apache MQ, application is MVC.NET 4.0 application, I found there is lot of inconsistent behavior while we try to invalidate the cache, both Tridion Object and DD4T cache are enabled.

Following is the observation

MVC.NET does not support JMS object messaging so a custom TextJMSCacheChannelConnector class needs to be used (https://github.com/dd4t/dd4t-cachechannel) to handle text messages at both deployer and website level

If we implement TextJMSCacheChannelConnector class Tridion Object Cache does not gets invalidated as HandleMessage method is not implemented in TextJMSCacheChannelConnector and HandleMessage method in JMSCacheChannelConnector class is not handling Text Message and throwing error "Message Type not supported"

If Default JMSCacheChannelConnector is used then Tridion object cache does get invalidated, however DD4T cache does not get invalidated because it uses TextJMSCacheChannelConnector and it is not capable of handling object messaging.

I think we might need to implement a HandleMessage method in TextJMSCacheChannelConnector to handle text based messages as well.

Regards, Sameer

**Comment by quirijnslings** [comment]
This looks like a possible bug, will investigate.

**Comment by rdhaundiyal** [comment]
Hi @quirijnslings , I requrested for a checkin in DD4t Project regarding this but didn't get any reply. As suggested by you at [https://tridion.stackexchange.com/questions/16338/dd4t-2-0-cache-not-getting-invalidated](https://tridion.stackexchange.com/questions/16338/dd4t-2-0-cache-not-getting-invalidated ) i have created a blog at https://rdhaundiyal.wordpress.com/2017/03/23/trdion-object-cache-apache-mq-base-invalidation/ Could you please check this and let me know if you see any issue.

**Comment by quirijnslings** [comment]
We have revised the whole cache invalidation and it is now working properly. Be careful to use the correct release: 1.3.0 for Tridion 9.0 and higher, 1.2.1 for older versions of Tridion.
